platform :ios, '6.0'
pod 'MJExtension', '~> 0.0.1'
pod 'MJRefresh', '~> 0.0.1'
pod 'FMDB', '~> 2.5'
pod 'CocoaHTTPServer', '~> 2.3'
pod 'Reachability', '~> 3.2'
pod 'SDWebImage', '~> 3.7.1'
pod 'UMengAnalytics-NO-IDFA'
pod 'JPushSDK', '~> 1.8.2'
pod 'WTRequestCenter', '~> 0.5.1'
pod 'AFNetworking', '~> 2.5.0'
pod 'SSKeychain', '~> 1.2.2'